import type { Property, Testimonial, Neighborhood, Agent } from '@/types';

export const agents: Agent[] = [
  {
    id: '1',
    name: 'Chinwe Okafor',
    phone: '+234 803 456 7890',
    email: 'chinwe@renthorizon.ng',
    whatsapp: '+234 803 456 7890',
    avatar: '/avatar-1.jpg',
    company: 'Elite Properties',
    isVerified: true,
    rating: 4.9,
    reviewCount: 127,
    listings: 45,
    location: 'Lekki, Lagos',
  },
  {
    id: '2',
    name: 'Emmanuel Adeyemi',
    phone: '+234 805 234 5678',
    email: 'emmanuel@renthorizon.ng',
    whatsapp: '+234 805 234 5678',
    avatar: '/avatar-2.jpg',
    company: 'Abuja Realty',
    isVerified: true,
    rating: 4.8,
    reviewCount: 89,
    listings: 32,
    location: 'Maitama, Abuja',
  },
  {
    id: '3',
    name: 'Ngozi Ibrahim',
    phone: '+234 807 876 5432',
    email: 'ngozi@renthorizon.ng',
    whatsapp: '+234 807 876 5432',
    avatar: '/avatar-3.jpg',
    company: 'PH Homes',
    isVerified: true,
    rating: 4.7,
    reviewCount: 64,
    listings: 28,
    location: 'GRA, Port Harcourt',
  },
];

export const properties: Property[] = [
  // Student Hostels
  {
    id: '1',
    title: 'Student Hostel - UNILAG Area',
    price: 150000,
    priceType: 'year',
    beds: 1,
    baths: 1,
    guests: 1,
    type: 'hostel',
    location: 'Akoka',
    state: 'Lagos',
    image: '/property-1.jpg',
    images: ['/property-1.jpg', '/property-2.jpg'],
    amenities: ['WiFi', 'Study Area', 'Security', 'Generator', 'Water'],
    availableFrom: '2024-09-01',
    description: 'Clean student hostel just 5 minutes walk from UNILAG. Shared kitchen, 24/7 security, and study areas. Perfect for students.',
    coordinates: { lat: 6.5244, lng: 3.3792 },
    agent: agents[0],
    isVerified: true,
    isInstantBook: false,
    rating: 4.5,
    reviewCount: 23,
    propertyCategory: 'student',
    minStay: 12,
  },
  {
    id: '2',
    title: 'Student Apartment - YabaTech',
    price: 250000,
    priceType: 'year',
    beds: 1,
    baths: 1,
    guests: 2,
    type: 'selfcon',
    location: 'Yaba',
    state: 'Lagos',
    image: '/property-2.jpg',
    images: ['/property-2.jpg', '/property-4.jpg'],
    amenities: ['WiFi', 'Kitchen', 'AC', 'Parking', 'Security'],
    availableFrom: '2024-08-15',
    description: 'Self-contain apartment ideal for YabaTech students. Private kitchen and bathroom. Close to campus.',
    coordinates: { lat: 6.5085, lng: 3.3841 },
    agent: agents[0],
    isVerified: true,
    isInstantBook: true,
    rating: 4.7,
    reviewCount: 18,
    propertyCategory: 'student',
    minStay: 6,
  },
  // Shortlets
  {
    id: '3',
    title: 'Luxury Shortlet - Lekki Phase 1',
    price: 35000,
    priceType: 'night',
    beds: 2,
    baths: 2,
    guests: 4,
    type: 'shortlet',
    location: 'Lekki Phase 1',
    state: 'Lagos',
    image: '/property-3.jpg',
    images: ['/property-3.jpg', '/property-5.jpg', '/property-6.jpg'],
    amenities: ['Pool', 'WiFi', 'AC', 'Smart TV', 'Kitchen', 'Parking', 'Gym'],
    availableFrom: '2024-01-01',
    description: 'Premium shortlet apartment with pool access. Fully furnished with modern amenities. Perfect for weekend getaways or business trips.',
    coordinates: { lat: 6.4474, lng: 3.4673 },
    agent: agents[0],
    isVerified: true,
    isInstantBook: true,
    rating: 4.9,
    reviewCount: 56,
    propertyCategory: 'shortlet',
    minStay: 1,
    maxStay: 30,
  },
  {
    id: '4',
    title: 'Cozy Shortlet - Victoria Island',
    price: 25000,
    priceType: 'night',
    beds: 1,
    baths: 1,
    guests: 2,
    type: 'shortlet',
    location: 'Victoria Island',
    state: 'Lagos',
    image: '/property-4.jpg',
    images: ['/property-4.jpg', '/property-7.jpg'],
    amenities: ['WiFi', 'AC', 'Netflix', 'Kitchen', 'Parking'],
    availableFrom: '2024-01-01',
    description: 'Beautiful studio shortlet in the heart of VI. Walking distance to restaurants and nightlife.',
    coordinates: { lat: 6.4281, lng: 3.4219 },
    agent: agents[0],
    isVerified: true,
    isInstantBook: true,
    rating: 4.6,
    reviewCount: 34,
    propertyCategory: 'shortlet',
    minStay: 1,
    maxStay: 14,
  },
  // Lounge Rooms
  {
    id: '5',
    title: 'Shared Lounge - Ikoyi',
    price: 8000,
    priceType: 'night',
    beds: 1,
    baths: 1,
    guests: 1,
    type: 'lounge',
    location: 'Ikoyi',
    state: 'Lagos',
    image: '/property-5.jpg',
    images: ['/property-5.jpg', '/property-1.jpg'],
    amenities: ['WiFi', 'Lounge Access', 'Breakfast', 'Housekeeping'],
    availableFrom: '2024-01-01',
    description: 'Comfortable lounge room in upscale Ikoyi residence. Shared living spaces with premium amenities.',
    coordinates: { lat: 6.455, lng: 3.436 },
    agent: agents[0],
    isVerified: true,
    isInstantBook: true,
    rating: 4.4,
    reviewCount: 12,
    propertyCategory: 'shortlet',
    minStay: 1,
    maxStay: 7,
  },
  // Apartments
  {
    id: '6',
    title: '2-Bedroom Flat - Gbagada',
    price: 1800000,
    priceType: 'year',
    beds: 2,
    baths: 2,
    guests: 4,
    type: 'apartment',
    location: 'Gbagada',
    state: 'Lagos',
    image: '/property-6.jpg',
    images: ['/property-6.jpg', '/property-2.jpg', '/property-4.jpg'],
    amenities: ['Parking', 'Security', 'Water', 'Prepaid Meter'],
    availableFrom: '2024-02-01',
    description: 'Spacious 2-bedroom flat in quiet Gbagada estate. Good for young professionals or small families.',
    coordinates: { lat: 6.5484, lng: 3.3923 },
    agent: agents[0],
    isVerified: true,
    isInstantBook: false,
    rating: 4.3,
    reviewCount: 8,
    propertyCategory: 'residential',
    minStay: 12,
  },
  // Shared Accommodation
  {
    id: '7',
    title: 'Shared Apartment - Room Available',
    price: 600000,
    priceType: 'year',
    beds: 1,
    baths: 1,
    guests: 1,
    type: 'shared',
    location: 'Ikeja',
    state: 'Lagos',
    image: '/property-7.jpg',
    images: ['/property-7.jpg', '/property-8.jpg'],
    amenities: ['WiFi', 'Shared Kitchen', 'Laundry', 'Security'],
    availableFrom: '2024-01-15',
    description: 'Private room in shared apartment with 2 other professionals. Shared kitchen and living room.',
    coordinates: { lat: 6.5957, lng: 3.3421 },
    agent: agents[0],
    isVerified: false,
    isInstantBook: false,
    rating: 4.1,
    reviewCount: 5,
    propertyCategory: 'residential',
    minStay: 6,
  },
  // Abuja Properties
  {
    id: '8',
    title: 'Student Hostel - UniAbuja',
    price: 180000,
    priceType: 'year',
    beds: 1,
    baths: 1,
    guests: 1,
    type: 'hostel',
    location: 'Gwagwalada',
    state: 'Abuja',
    image: '/property-8.jpg',
    images: ['/property-8.jpg', '/property-9.jpg'],
    amenities: ['WiFi', 'Study Room', 'Security', 'Water'],
    availableFrom: '2024-09-01',
    description: 'Affordable student hostel near University of Abuja. Quiet environment for studying.',
    coordinates: { lat: 8.9419, lng: 7.0815 },
    agent: agents[1],
    isVerified: true,
    isInstantBook: false,
    rating: 4.2,
    reviewCount: 15,
    propertyCategory: 'student',
    minStay: 12,
  },
  {
    id: '9',
    title: 'Shortlet Apartment - Maitama',
    price: 45000,
    priceType: 'night',
    beds: 2,
    baths: 2,
    guests: 4,
    type: 'shortlet',
    location: 'Maitama',
    state: 'Abuja',
    image: '/property-9.jpg',
    images: ['/property-9.jpg', '/property-1.jpg', '/property-3.jpg'],
    amenities: ['Pool', 'Gym', 'WiFi', 'AC', 'Smart TV', 'Parking'],
    availableFrom: '2024-01-01',
    description: 'Luxury shortlet in upscale Maitama. Perfect for diplomats and business travelers.',
    coordinates: { lat: 9.0765, lng: 7.3986 },
    agent: agents[1],
    isVerified: true,
    isInstantBook: true,
    rating: 4.8,
    reviewCount: 42,
    propertyCategory: 'shortlet',
    minStay: 1,
    maxStay: 30,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Adaobi Nwachukwu',
    role: 'UNILAG Student',
    avatar: '/avatar-1.jpg',
    quote: 'Found my hostel in Akoka within 2 days. The AI helped me find exactly what I needed near campus.',
    rating: 5,
    location: 'Lagos',
  },
  {
    id: '2',
    name: 'Michael Ojo',
    role: 'Business Traveler',
    avatar: '/avatar-2.jpg',
    quote: 'Booked a shortlet in VI for my business trip. Instant booking feature saved me so much time!',
    rating: 5,
    location: 'Abuja',
  },
  {
    id: '3',
    name: 'Fatima Abdullahi',
    role: 'NYSC Member',
    avatar: '/avatar-3.jpg',
    quote: 'Found affordable accommodation during my service year. The student filter was super helpful.',
    rating: 5,
    location: 'Kano',
  },
];

export const neighborhoods: Neighborhood[] = [
  {
    id: '1',
    name: 'Akoka / UNILAG',
    state: 'Lagos',
    image: '/neighborhood-1.jpg',
    listingCount: 145,
    avgPrice: 200000,
  },
  {
    id: '2',
    name: 'Lekki Phase 1',
    state: 'Lagos',
    image: '/neighborhood-2.jpg',
    listingCount: 89,
    avgPrice: 35000,
  },
  {
    id: '3',
    name: 'Maitama',
    state: 'Abuja',
    image: '/neighborhood-3.jpg',
    listingCount: 67,
    avgPrice: 42000,
  },
  {
    id: '4',
    name: 'Yaba / YabaTech',
    state: 'Lagos',
    image: '/neighborhood-4.jpg',
    listingCount: 112,
    avgPrice: 280000,
  },
  {
    id: '5',
    name: 'Victoria Island',
    state: 'Lagos',
    image: '/neighborhood-5.jpg',
    listingCount: 78,
    avgPrice: 28000,
  },
];

export const amenitiesList = [
  'WiFi',
  'AC',
  'Parking',
  'Security',
  'Generator',
  'Water',
  'Kitchen',
  'Pool',
  'Gym',
  'Laundry',
  'Study Area',
  'Smart TV',
  'Netflix',
  'Housekeeping',
  'Breakfast',
];

export const propertyTypes = [
  { value: 'hostel', label: 'Student Hostel', category: 'student' },
  { value: 'selfcon', label: 'Self-Contain', category: 'student' },
  { value: 'shortlet', label: 'Shortlet', category: 'shortlet' },
  { value: 'lounge', label: 'Lounge Room', category: 'shortlet' },
  { value: 'apartment', label: 'Apartment', category: 'residential' },
  { value: 'shared', label: 'Shared Room', category: 'residential' },
  { value: 'room', label: 'Single Room', category: 'residential' },
];

export const nigerianStates = [
  'Lagos',
  'Abuja',
  'Port Harcourt',
  'Ibadan',
  'Kano',
  'Enugu',
  'Benin City',
];

export const priceRanges = [
  { label: 'Under ₦100K', min: 0, max: 100000 },
  { label: '₦100K - ₦300K', min: 100000, max: 300000 },
  { label: '₦300K - ₦500K', min: 300000, max: 500000 },
  { label: '₦500K - ₦1M', min: 500000, max: 1000000 },
  { label: '₦1M+', min: 1000000, max: 999999999 },
];
